name: ViDesk
options:
  bundleIdPrefix: com.videsk
  deploymentTarget:
    visionOS: "2.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    SWIFT_VERSION: "5.9"

targets:
  ViDesk:
    type: application
    platform: visionOS
    sources:
      - path: ViDesk
        excludes:
          - "**/.git/**"
          - "**/README.md"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.videsk.app
        INFOPLIST_FILE: ViDesk/Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_OBJC_BRIDGING_HEADER: ViDesk/ViDesk-Bridging-Header.h
        # FreeRDP 库配置
        LIBRARY_SEARCH_PATHS:
          - "$(PROJECT_DIR)/FreeRDPFramework/lib"
        OTHER_LDFLAGS:
          - "-lfreerdp3"
          - "-lfreerdp-client3"
          - "-lwinpr3"
          - "-lcjson"
          - "-lssl"
          - "-lcrypto"
          - "-lz"
        HEADER_SEARCH_PATHS:
          - "$(PROJECT_DIR)/FreeRDPFramework/include"
        # Metal 着色器
        MTL_HEADER_SEARCH_PATHS: "$(PROJECT_DIR)/ViDesk/Core/Rendering/Shaders"
        # visionOS 特定设置
        SUPPORTED_PLATFORMS: xros xrsimulator
        TARGETED_DEVICE_FAMILY: "7"
        # C 语言设置
        CLANG_ENABLE_MODULES: YES
        GCC_C_LANGUAGE_STANDARD: c11
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
          DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
          DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
          SWIFT_COMPILATION_MODE: wholemodule
    dependencies: []

schemes:
  ViDesk:
    build:
      targets:
        ViDesk: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
